### 1. Listar gastos (Debería salir lista vacía al principio)
GET http://localhost:8080/api/gastos

### 2. Guardar un gasto de prueba
POST http://localhost:8080/api/gastos
Content-Type: application/json

{
  "descripcion": "Reparación de Portero Eléctrico",
  "monto": 15000.50,
  "fechaGasto": "2024-02-20",
  "esExtraordinario": false
}

### 3. Intentar guardar gasto con error (Monto negativo)
POST http://localhost:8080/api/gastos
Content-Type: application/json

{
  "descripcion": "Gasto invalido",
  "monto": -500.00,
  "fechaGasto": "2024-02-20",
  "esExtraordinario": false
}